name: Deploy to Azure App Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - force-rebuild
          - skip-cache
      deploy_database:
        description: 'Run database migrations'
        required: false
        default: true
        type: boolean
      custom_message:
        description: 'Custom deployment message'
        required: false
        default: 'Manual deployment'
        type: string

env:
  AZURE_WEBAPP_NAME: app-byteSmith-CUS
  AZURE_WEBAPP_PACKAGE_PATH: '.'           # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                     # set this to the node version to use

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE4998685E7A4B529B9C22B2759AA4F1 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_428DC6E42F6C41038B126ED3F4E5A944 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5091F30AC60E43BC9EE61A1F38D50876 }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ "${{ github.event.inputs.build_mode }}" == "skip-cache" ]; then
          npm ci --no-cache
        elif [ "${{ github.event.inputs.build_mode }}" == "force-rebuild" ]; then
          rm -rf node_modules package-lock.json
          npm install
        else
          npm ci
        fi

    - name: Display deployment info
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Manual deployment triggered"
        echo "Build mode: ${{ github.event.inputs.build_mode }}"
        echo "Database migrations: ${{ github.event.inputs.deploy_database }}"
        echo "Message: ${{ github.event.inputs.custom_message }}"

    - name: Build application for Azure
      run: node build-azure.js

    - name: Run database migrations (if enabled)
      if: github.event.inputs.deploy_database == 'true' && env.DATABASE_URL != ''
      run: |
        echo "Running database migrations..."
        npm run db:push || echo "Database migrations skipped (no DATABASE_URL)"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE4998685E7A4B529B9C22B2759AA4F1 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_428DC6E42F6C41038B126ED3F4E5A944 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5091F30AC60E43BC9EE61A1F38D50876 }}


    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Post-deployment notification
      if: always()
      run: |
        if [ "${{ steps.deploy-to-webapp.outcome }}" == "success" ]; then
          echo "✅ Deployment completed successfully!"
          echo "🌐 Website URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "📝 Custom message: ${{ github.event.inputs.custom_message }}"
          fi
        else
          echo "❌ Deployment failed!"
        fi